application: graphpredict
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
# - url: /favicon\.ico
#   static_files: favicon.ico
#   upload: favicon\.ico

- url: .*
  script: project.wsgi.application


# libraries:
# - name: webapp2
#   version: "2.5.2"
libraries:
- name: MySQLdb
  version: 1.2.5

- name: django
  version: "1.8.3"