application: gradeprediction
version: 1
runtime: python27
api_version: 1
threadsafe: yes

  # [START django_app]

handlers:
- url: /static
  static_dir: static/

- url: .*
  script: project.wsgi.application

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK 
libraries:
- name: MySQLdb
  version: 1.2.5

- name: numpy
  version: "1.6.1"


# [END django_app]
